Repository piqueserver/piqueserver, pull requests merged in 2018-02, with the labels that each got.

#284 Make copytree not fail if dst dir. already exists
  piqueserver/run.py
  tests/piqueserver/test_run.py
Labels: PR: improvement

#280 Add stricter checks to Existingplayer
  pyspades/player.py
Labels: PR: solve-bug

#298 Merge goto/gotos/move into move/moves
  piqueserver/config/config.json
  piqueserver/config/config.toml
  piqueserver/core_commands/__init__.py
  piqueserver/core_commands/movement.py
Labels: PR: refactoring, core commands

#271 Register Packets at Runtime
  pyspades/contained.pyx
  pyspades/packet.pyx
Labels: PR: refactoring

#310 Add PermissionDenied exception
  piqueserver/commands.py
  piqueserver/core_commands/player.py
Labels: PR: improvement

#309 add method to make an untrusted set of coords safe
  pyspades/player.py
  pyspades/server.py
  pyspades/vxl.pxd
  pyspades/vxl.pyx
  pyspades/vxl_c.h
Labels: PR: solve-bug, must-have
