Repository piqueserver/piqueserver, pull requests merged in 2019-12, with the labels that each got.

#550 Updating Readme
  README.rst
Labels: PR: modify-text-file(s)

#537 Update Push Game Mode
  piqueserver/game_modes/push.py
Labels: PR: gamemodes

#557 Change Documentation Layout, add a Linux example
  doc/admins.rst
  doc/developers.rst
  doc/index.rst
  doc/systemd-install-setup.rst
Labels: PR: docs

#566 Improve doc for Push
  piqueserver/game_modes/push.py
Labels: PR: docs
