Repository piqueserver/piqueserver, pull requests merged in 2019-08, with the labels that each got.

#539 Fix checking connection is a player
  piqueserver/core_commands/game.py
  piqueserver/core_commands/info.py
  piqueserver/core_commands/moderation.py
  piqueserver/core_commands/movement.py
  piqueserver/core_commands/player.py
  piqueserver/core_commands/server.py
  piqueserver/scripts/afk.py
  piqueserver/scripts/airstrike2.py
  piqueserver/scripts/analyze.py
  piqueserver/scripts/badmin.py
  piqueserver/scripts/blockinfo.py
  piqueserver/scripts/geoip.py
  piqueserver/scripts/markers.py
  piqueserver/scripts/paint.py
  piqueserver/scripts/rapid.py
  piqueserver/scripts/ratio.py
  piqueserver/scripts/runningman.py
  piqueserver/scripts/votemap.py
Labels: PR: solve-bug

#544 Replace imp with importlib
  piqueserver/extensions.py
Labels: WIP

#536 Preserve existing blocks during linebuild
  pyspades/player.py
Labels: PR: improvement
