Repository piqueserver/piqueserver, pull requests merged in 2019-04, with the labels that each got.

#484 work around DelayedCall.reset() issue in all places
  piqueserver/scripts/airstrike2.py
  piqueserver/server.py
Labels: PR: solve-bug

#479 Add new release notification
  piqueserver/config/config.toml
  piqueserver/player.py
  piqueserver/release.py
  piqueserver/server.py
  requirements.txt
  setup.py
  tests/piqueserver/test_release.py
Labels: PR: new-feature, WIP

#490 Basic UTF-8 encoding support
  pyspades/common.pyx
  requirements.txt
  setup.py
  tox.ini
Labels: PR: improvement
